insert into airport (id, name, country, city) values ('NGK', 'Nogliki Airport', 'RU', 'Yanweigang');
insert into airport (id, name, country, city) values ('MUP', 'Mulga Park Airport', 'AU', 'Hödrögö');
insert into airport (id, name, country, city) values ('OKN', 'Okondja Airport', 'GA', 'Linfen');
insert into airport (id, name, country, city) values ('XNT', 'Xingtai Dalian Airport', 'CN', 'Baitang');
insert into airport (id, name, country, city) values ('IRN', 'Iriona Airport', 'HN', 'Songzhuang');
insert into airport (id, name, country, city) values ('MIN', 'Minnipa Airport', 'AU', 'Lavaur');
insert into airport (id, name, country, city) values ('MLA', 'Malta International Airport', 'MT', 'Putou');
insert into airport (id, name, country, city) values ('MFY', 'Maradi Airport', 'NE', 'Akhtarīn');
insert into airport (id, name, country, city) values ('MFW', 'Grenchen Airport', 'CH', 'Impendle');
insert into airport (id, name, country, city) values ('KID', 'Kristianstad Airport', 'SE', 'Madrid');
insert into airport (id, name, country, city) values ('EJH', 'Al Wajh Domestic Airport', 'SA', 'Caldas das Taipas');
insert into airport (id, name, country, city) values ('EXI', 'Excursion Inlet Seaplane Base', 'US', 'Richards Bay');
insert into airport (id, name, country, city) values ('KEG', 'Keglsugl Airport', 'PG', 'Chicago');
insert into airport (id, name, country, city) values ('BDL', 'Bradley International Airport', 'US', 'Wulan');
insert into airport (id, name, country, city) values ('YVG', 'Vermilion Airport', 'CA', 'Bacnor East');
insert into airport (id, name, country, city) values ('KMM', 'Kimaam Airport', 'ID', 'Sundsvall');
insert into airport (id, name, country, city) values ('RFP', 'Raiatea Airport', 'PF', 'Tupambaé');
insert into airport (id, name, country, city) values ('LEH', 'Le Havre Octeville Airport', 'FR', 'Klayusiwalan');
insert into airport (id, name, country, city) values ('BXB', 'Babo Airport', 'ID', 'Louisville');
insert into airport (id, name, country, city) values ('AME', 'Alto Molocue Airport', 'MZ', 'Ostrówek');
insert into airport (id, name, country, city) values ('NDY', 'Sanday Airport', 'GB', 'North Cowichan');
insert into airport (id, name, country, city) values ('MSZ', 'Namibe Airport', 'AO', 'Junbu');
insert into airport (id, name, country, city) values ('PEE', 'Bolshoye Savino Airport', 'RU', 'Khyzy');
insert into airport (id, name, country, city) values ('TCG', 'Tacheng Airport', 'CN', 'Castelo de Vide');
insert into airport (id, name, country, city) values ('KGF', 'Sary-Arka Airport', 'KZ', 'Selasari');
insert into airport (id, name, country, city) values ('RQO', 'El Reno Regional Airport', 'US', 'Oslo');
insert into airport (id, name, country, city) values ('YHB', 'Hudson Bay Airport', 'CA', 'Banjar Jagasatru');
insert into airport (id, name, country, city) values ('KOI', 'Kirkwall Airport', 'GB', 'Huangling');
insert into airport (id, name, country, city) values ('TVI', 'Thomasville Regional Airport', 'US', 'Krasnoznamensk');
insert into airport (id, name, country, city) values ('FME', 'Tipton Airport', 'US', 'Rouen');
insert into airport (id, name, country, city) values ('LND', 'Hunt Field', 'US', 'Retorta');
insert into airport (id, name, country, city) values ('BTW', 'Barter Island LRRS Airport', 'US', 'Manadhoo');
insert into airport (id, name, country, city) values ('BCQ', 'Brak Airport', 'LY', 'Cernache do Bonjardim');
insert into airport (id, name, country, city) values ('RNR', 'Robinson River Airport', 'PG', 'Dabu');
insert into airport (id, name, country, city) values ('CHR', 'Châteauroux-Déols "Marcel Dassault" Airport', 'FR', 'Perez');
insert into airport (id, name, country, city) values ('NGX', 'Manang Airport', 'NP', 'Vale de Santarém');
insert into airport (id, name, country, city) values ('YZU', 'Whitecourt Airport', 'CA', 'Pápa');
insert into airport (id, name, country, city) values ('MYV', 'Yuba County Airport', 'US', 'Estrada');
insert into airport (id, name, country, city) values ('EAR', 'Kearney Regional Airport', 'US', 'Mokronog');
insert into airport (id, name, country, city) values ('CEX', 'Chena Hot Springs Airport', 'US', 'Pedrulheira');
insert into airport (id, name, country, city) values ('AFI', 'Amalfi Airport', 'CO', 'Ţāmiyah');
insert into airport (id, name, country, city) values ('KEK', 'Ekwok Airport', 'US', 'Tubod');
insert into airport (id, name, country, city) values ('AKT', 'RAF Akrotiri', 'GB', 'Aparecida de Goiânia');
insert into airport (id, name, country, city) values ('KGZ', 'Glacier Creek Airport', 'US', 'Louny');
insert into airport (id, name, country, city) values ('HTY', 'Hatay Airport', 'TR', 'Leigongmiao');
insert into airport (id, name, country, city) values ('SWH', 'Swan Hill Airport', 'AU', 'Jianqiao');
insert into airport (id, name, country, city) values ('ZAM', 'Zamboanga International Airport', 'PH', 'Puncaktugu');
insert into airport (id, name, country, city) values ('SAT', 'San Antonio International Airport', 'US', 'Jandaia do Sul');
insert into airport (id, name, country, city) values ('ROO', 'Maestro Marinho Franco Airport', 'BR', 'Dabu');
insert into airport (id, name, country, city) values ('YBK', 'Baker Lake Airport', 'CA', 'Néos Mylótopos');
insert into airport (id, name, country, city) values ('YBW', 'Patrocínio Airport', 'BR', 'Tigarunggu');
insert into airport (id, name, country, city) values ('OKP', 'Oksapmin Airport', 'PG', 'Luo’ao');
insert into airport (id, name, country, city) values ('BCZ', 'Milyakburra Airport', 'AU', 'København');
insert into airport (id, name, country, city) values ('BRX', 'Maria Montez International Airport', 'DO', 'Jardim da Serra');
insert into airport (id, name, country, city) values ('CLS', 'Chehalis Centralia Airport', 'US', 'Madette');
insert into airport (id, name, country, city) values ('REY', 'Reyes Airport', 'BO', 'Vysoké nad Jizerou');
insert into airport (id, name, country, city) values ('BKW', 'Raleigh County Memorial Airport', 'US', 'Chambara');
insert into airport (id, name, country, city) values ('UTU', 'Ustupo Airport', 'PA', 'Kuala Terengganu');
insert into airport (id, name, country, city) values ('RRT', 'Warroad International Memorial Airport', 'US', 'Montpellier');
insert into airport (id, name, country, city) values ('KBW', 'Kabala Airport', 'SL', 'Samphanthawong');
insert into airport (id, name, country, city) values ('DBO', 'Dubbo City Regional Airport', 'AU', 'North Side');
insert into airport (id, name, country, city) values ('NKM', 'Nagoya Airport', 'JP', 'Xieshui');
insert into airport (id, name, country, city) values ('PWL', 'Purwokerto Airport', 'ID', 'Värmdö');
insert into airport (id, name, country, city) values ('SOW', 'Show Low Regional Airport', 'US', 'Fresno');
insert into airport (id, name, country, city) values ('IJU', 'Ijuí Airport', 'BR', 'Jialu');
insert into airport (id, name, country, city) values ('LTQ', 'Iaciara Airport', 'BR', 'Anaco');
insert into airport (id, name, country, city) values ('DAZ', 'Darwaz Airport', 'AF', 'Philadelphia');
insert into airport (id, name, country, city) values ('COS', 'City of Colorado Springs Municipal Airport', 'US', 'Zhouji');
insert into airport (id, name, country, city) values ('TUL', 'Tulsa International Airport', 'US', 'San Juan');
insert into airport (id, name, country, city) values ('IOW', 'Iowa City Municipal Airport', 'US', 'Maibu');
insert into airport (id, name, country, city) values ('CGR', 'Campo Grande Airport', 'BR', 'Mosoc Llacta');
insert into airport (id, name, country, city) values ('YWM', 'Williams Harbour Airport', 'CA', 'Kobeřice');
insert into airport (id, name, country, city) values ('BDR', 'Igor I Sikorsky Memorial Airport', 'US', 'Andaray');
insert into airport (id, name, country, city) values ('HSS', 'Hissar Airport', 'IN', 'Bacnotan');
insert into airport (id, name, country, city) values ('KTD', 'Kitadaito Airport', 'JP', 'Cipadung Timur');
insert into airport (id, name, country, city) values ('CNN', 'Kannur International Airport', 'IN', 'Mpongwe');
insert into airport (id, name, country, city) values ('CEM', 'Central Airport', 'US', 'Banatsko Veliko Selo');
insert into airport (id, name, country, city) values ('JAX', 'Jacksonville International Airport', 'US', 'Bambous Virieux');
insert into airport (id, name, country, city) values ('VVC', 'Vanguardia Airport', 'CO', 'Duas Igrejas');
insert into airport (id, name, country, city) values ('FUG', 'Fuyang Xiguan Airport', 'CN', 'Dobri Dol');
insert into airport (id, name, country, city) values ('UTH', 'Udon Thani Airport', 'TH', 'Xipu');
insert into airport (id, name, country, city) values ('UTA', 'Mutare Airport', 'ZW', 'Saurama');
insert into airport (id, name, country, city) values ('BGR', 'Bangor International Airport', 'US', 'Sirnaresmi');
insert into airport (id, name, country, city) values ('DHN', 'Dothan Regional Airport', 'US', 'Novopokrovka');
insert into airport (id, name, country, city) values ('PAY', 'Pamol Airport', 'MY', 'Can-asujan');
insert into airport (id, name, country, city) values ('FFA', 'First Flight Airport', 'US', 'Slavyanovo');
insert into airport (id, name, country, city) values ('MGS', 'Mangaia Island Airport', 'CK', 'Pinar del Río');
insert into airport (id, name, country, city) values ('BHT', 'Brighton Downs Airport', 'AU', 'Örebro');
insert into airport (id, name, country, city) values ('CIH', 'Changzhi Airport', 'CN', 'Itaí');
insert into airport (id, name, country, city) values ('WCH', 'Chaitén Airport', 'CL', 'Vlachovice');
insert into airport (id, name, country, city) values ('DNN', 'Dalton Municipal Airport', 'US', 'Preserje pri Radomljah');
insert into airport (id, name, country, city) values ('OGS', 'Ogdensburg International Airport', 'US', 'Duozhu');
insert into airport (id, name, country, city) values ('PHT', 'Henry County Airport', 'US', 'Palhoça');
insert into airport (id, name, country, city) values ('FAA', 'Faranah Airport', 'GN', 'Xingquan');
insert into airport (id, name, country, city) values ('RVR', 'Green River Municipal Airport', 'US', 'Danderyd');
insert into airport (id, name, country, city) values ('YNT', 'Yantai Laishan Airport', 'CN', 'Troitskoye');
insert into airport (id, name, country, city) values ('KRD', 'Kurundi Airport', 'AU', 'Concepcion');
insert into airport (id, name, country, city) values ('IKT', 'Irkutsk Airport', 'RU', 'Yangambi');
insert into airport (id, name, country, city) values ('IUE', 'Niue International Airport', 'NU', 'Berovo');
insert into airport (id, name, country, city) values ('MPE', 'Griswold Airport', 'US', 'Shikārpur');
insert into airport (id, name, country, city) values ('POV', 'Prešov Air Base', 'SK', 'Pinyug');
insert into airport (id, name, country, city) values ('CDA', 'Cooinda Airport', 'AU', 'Santiago');
insert into airport (id, name, country, city) values ('MGW', 'Aden Adde International Airport', 'SO', 'Qiaochong');
insert into airport (id, name, country, city) values ('VFA', 'Victoria Falls International Airport', 'ZW', 'Lộc Bình');
insert into airport (id, name, country, city) values ('BHU', 'Bhavnagar Airport', 'IN', 'Dondo');
insert into airport (id, name, country, city) values ('MIH', 'Mitchell Plateau Airport', 'AU', 'Macapo');
insert into airport (id, name, country, city) values ('ELF', 'El Fasher Airport', 'SD', 'Puttalam');
insert into airport (id, name, country, city) values ('RMD', 'Basanth Nagar Airport', 'IN', 'Alkmaar');
insert into airport (id, name, country, city) values ('XMW', 'Montauban Airport', 'FR', 'Puerto López');
insert into airport (id, name, country, city) values ('THG', 'Thangool Airport', 'AU', 'Dolno Palčište');
insert into airport (id, name, country, city) values ('LOA', 'Lorraine Airport', 'AU', 'Maayong Tubig');
insert into airport (id, name, country, city) values ('POO', 'Poços de Caldas - Embaixador Walther Moreira Salles Airport', 'BR', 'Cullhuas');
insert into airport (id, name, country, city) values ('GUM', 'Antonio B. Won Pat International Airport', 'GU', 'Buenavista');
insert into airport (id, name, country, city) values ('LEN', 'Leon Airport', 'ES', 'Labinot-Mal');
insert into airport (id, name, country, city) values ('MVE', 'Montevideo Chippewa County Airport', 'US', 'Lakshmīpur');
insert into airport (id, name, country, city) values ('AUE', 'Abu Rudeis Airport', 'EG', 'Arosbaya');
insert into airport (id, name, country, city) values ('ZYL', 'Osmany International Airport', 'BD', 'Badian');
insert into airport (id, name, country, city) values ('REE', 'Reese Airpark', 'US', 'Štítina');
insert into airport (id, name, country, city) values ('LWW', 'Gyumri Shirak Airport', 'AM', 'Anto');
insert into airport (id, name, country, city) values ('GVW', 'Richards-Gebaur Air Force Base', 'US', 'Guoduwan');
insert into airport (id, name, country, city) values ('TPN', 'Tiputini Airport', 'EC', 'Barurao');
insert into airport (id, name, country, city) values ('PGO', 'Stevens Field', 'US', 'Jiujie');
insert into airport (id, name, country, city) values ('WTL', 'Tuntutuliak Airport', 'US', 'Omigawa');
insert into airport (id, name, country, city) values ('SHR', 'Sheridan County Airport', 'US', 'Tomteboda');
insert into airport (id, name, country, city) values ('LDZ', 'Londolozi Airport', 'ZA', 'Ostrów Lubelski');
insert into airport (id, name, country, city) values ('ENI', 'El Nido Airport', 'PH', 'Zaria');
insert into airport (id, name, country, city) values ('TEE', 'Cheikh Larbi Tébessi Airport', 'DZ', 'Fareydūnshahr');
insert into airport (id, name, country, city) values ('WTD', 'West End Airport', 'BS', 'Banjar Cemenggon');
insert into airport (id, name, country, city) values ('YVE', 'Vernon Airport', 'CA', 'Palekastro');
insert into airport (id, name, country, city) values ('YYS', 'Blissville Airport', 'CA', 'Tai’an');
insert into airport (id, name, country, city) values ('JJD', 'Comandante Ariston Pessoa Airport', 'BR', 'Tiflet');
insert into airport (id, name, country, city) values ('IVR', 'Inverell Airport', 'AU', 'Yantianhe');
insert into airport (id, name, country, city) values ('DMO', 'Sedalia Memorial Airport', 'US', 'Bang Saphan');
insert into airport (id, name, country, city) values ('KPA', 'Kopiago Airport', 'PG', 'Manturovo');
insert into airport (id, name, country, city) values ('KAB', 'Kariba International Airport', 'ZW', 'Francisco Beltrão');
insert into airport (id, name, country, city) values ('SXH', 'Sehulea Airport', 'PG', 'Al Buq‘ah');
insert into airport (id, name, country, city) values ('LWY', 'Lawas Airport', 'MY', 'Bjärred');
insert into airport (id, name, country, city) values ('NNI', 'Namutoni Airport', 'NA', 'Ḩabūr');
insert into airport (id, name, country, city) values ('BSL', 'EuroAirport Basel-Mulhouse-Freiburg Airport', 'FR', 'Zhenqian');
insert into airport (id, name, country, city) values ('ANL', 'Andulo Airport', 'AO', 'Thanh Khê');
insert into airport (id, name, country, city) values ('XJM', 'Mangla Airport', 'PK', 'Ajaccio');
insert into airport (id, name, country, city) values ('SUZ', 'Suria Airport', 'PG', 'Beloye');
insert into airport (id, name, country, city) values ('POI', 'Capitan Nicolas Rojas Airport', 'BO', 'Phoenix');
insert into airport (id, name, country, city) values ('XIQ', 'Ilimanaq Heliport', 'GL', 'Bollnäs');
insert into airport (id, name, country, city) values ('MDV', 'Médouneu Airport', 'GQ', 'Alençon');
insert into airport (id, name, country, city) values ('TMJ', 'Termez Airport', 'UZ', 'Elverum');
insert into airport (id, name, country, city) values ('INI', 'Nis Airport', 'RS', 'Taraju');
insert into airport (id, name, country, city) values ('BES', 'Brest Bretagne Airport', 'FR', 'Idi Iroko');
insert into airport (id, name, country, city) values ('GMZ', 'La Gomera Airport', 'ES', 'Satinka');
insert into airport (id, name, country, city) values ('PUB', 'Pueblo Memorial Airport', 'US', 'Hlusk');
insert into airport (id, name, country, city) values ('ELI', 'Elim Airport', 'US', 'Fengxian');
insert into airport (id, name, country, city) values ('EVH', 'Evans Head Aerodrome', 'AU', 'Carvalhal');
insert into airport (id, name, country, city) values ('TCM', 'McChord Air Force Base', 'US', 'Chachagüí');
insert into airport (id, name, country, city) values ('FPR', 'St Lucie County International Airport', 'US', 'Sadao');
insert into airport (id, name, country, city) values ('GJA', 'La Laguna Airport', 'HN', 'Jiuxian');
insert into airport (id, name, country, city) values ('SLQ', 'Sleetmute Airport', 'US', 'Przywidz');
insert into airport (id, name, country, city) values ('XBG', 'Bogande Airport', 'BF', 'Panitian');
insert into airport (id, name, country, city) values ('HRC', 'Sary Su Airport', 'KZ', 'Qixingtai');
insert into airport (id, name, country, city) values ('BAU', 'Bauru Airport', 'BR', 'Princeton');
insert into airport (id, name, country, city) values ('USA', 'Concord-Padgett Regional Airport', 'US', 'Limoeiro do Norte');
insert into airport (id, name, country, city) values ('QUG', 'Chichester/Goodwood Airport', 'GB', 'Metz');
insert into airport (id, name, country, city) values ('MCB', 'Mc Comb/Pike County Airport/John E Lewis Field', 'US', 'Batsari');
insert into airport (id, name, country, city) values ('AGH', 'Ängelholm-Helsingborg Airport', 'SE', 'Emiliano Zapata');
insert into airport (id, name, country, city) values ('QLF', 'Lahti Vesivehmaa Airport', 'FI', 'Novais');
insert into airport (id, name, country, city) values ('HZB', 'Merville-Calonne Airport', 'FR', 'Dobdoban');
insert into airport (id, name, country, city) values ('SFM', 'Sanford Seacoast Regional Airport', 'US', 'Puente Nacional');
insert into airport (id, name, country, city) values ('GXG', 'Negage Airport', 'AO', 'Orerokpe');
insert into airport (id, name, country, city) values ('LRO', 'Sharpe AAF', 'US', 'Oenopu');
insert into airport (id, name, country, city) values ('BIJ', 'Biliau Airport', 'PG', 'Pedrulheira');
insert into airport (id, name, country, city) values ('PGB', 'Pangoa Airport', 'PG', 'Phetchabun');
insert into airport (id, name, country, city) values ('BAM', 'Battle Mountain Airport', 'US', 'Buikwe');
insert into airport (id, name, country, city) values ('CUE', 'Mariscal Lamar Airport', 'EC', 'Osiedle-Nowiny');
insert into airport (id, name, country, city) values ('ITE', 'Ituberá Airport', 'BR', 'Lumby');
insert into airport (id, name, country, city) values ('BHX', 'Birmingham International Airport', 'GB', 'Encrucijada');
insert into airport (id, name, country, city) values ('CMV', 'Coromandel Aerodrome', 'NZ', 'Krasnyye Chetai');
insert into airport (id, name, country, city) values ('THI', 'Tichitt Airport', 'MR', 'Noyelles-sous-Lens');
insert into airport (id, name, country, city) values ('IVA', 'Ampampamena Airport', 'MG', 'Tashtagol');
insert into airport (id, name, country, city) values ('CBC', 'Cherrabun Airport', 'AU', 'Ndofane');
insert into airport (id, name, country, city) values ('ZHI', 'Grenchen Airport', 'CH', 'Arshaluys');
insert into airport (id, name, country, city) values ('CSB', 'Caransebeş Airport', 'RO', 'Damiao');
insert into airport (id, name, country, city) values ('UPR', 'Upiara Airport', 'PG', 'Iwŏn-ŭp');
insert into airport (id, name, country, city) values ('DTA', 'Delta Municipal Airport', 'US', 'San Manuel');
insert into airport (id, name, country, city) values ('NGI', 'Ngau Airport', 'FJ', 'Millerovo');
insert into airport (id, name, country, city) values ('SMJ', 'Sim Airport', 'PG', 'Rutul');
insert into airport (id, name, country, city) values ('BZZ', 'RAF Brize Norton', 'GB', 'Chirpan');
insert into airport (id, name, country, city) values ('SOM', 'San Tomé Airport', 'VE', 'Neepawa');
insert into airport (id, name, country, city) values ('QSZ', 'Yeerqiang Airport', 'CN', 'Jacksonville');
insert into airport (id, name, country, city) values ('DLR', 'Dalnerechensk Airport', 'RU', 'Torre do Pinhão');
insert into airport (id, name, country, city) values ('VAW', 'Vardø Airport, Svartnes', 'NO', 'Thorpe');
insert into airport (id, name, country, city) values ('ABU', 'Haliwen Airport', 'ID', 'Kutorejo');
insert into airport (id, name, country, city) values ('MFQ', 'Maradi Airport', 'NE', 'Eséka');
insert into airport (id, name, country, city) values ('OSK', 'Oskarshamn Airport', 'SE', 'Lovas');
insert into airport (id, name, country, city) values ('LEX', 'Blue Grass Airport', 'US', 'Padangguci');
insert into airport (id, name, country, city) values ('MDC', 'Sam Ratulangi Airport', 'ID', 'Bocowanti');
insert into airport (id, name, country, city) values ('MXR', 'Moussoro Airport', 'TD', 'Nyachera');
insert into airport (id, name, country, city) values ('USN', 'Ulsan Airport', 'KR', 'Lipljan');
insert into airport (id, name, country, city) values ('EAB', 'Abbse Airport', 'YE', 'San Pablo');
insert into airport (id, name, country, city) values ('NLH', 'Ninglang Luguhu Airport', 'CN', 'Boyany');
insert into airport (id, name, country, city) values ('IBO', 'Ibo Airport', 'MZ', 'Luozhuang');
insert into airport (id, name, country, city) values ('MMC', 'Ciudad Mante National Airport', 'MX', 'Qinghe');
insert into airport (id, name, country, city) values ('MLI', 'Quad City International Airport', 'US', 'Xiling');
insert into airport (id, name, country, city) values ('DGU', 'Dedougou Airport', 'BF', 'Clermont-Ferrand');
insert into airport (id, name, country, city) values ('CEW', 'Bob Sikes Airport', 'US', 'Cimo de Vila');
insert into airport (id, name, country, city) values ('JIW', 'Jiwani Airport', 'PK', 'Rájec-Jestřebí');
insert into airport (id, name, country, city) values ('FPO', 'Grand Bahama International Airport', 'BS', 'Muang Sam Sip');
insert into airport (id, name, country, city) values ('CUU', 'General Roberto Fierro Villalobos International Airport', 'MX', 'Hirvensalmi');
insert into airport (id, name, country, city) values ('BLY', 'Belmullet Aerodrome', 'IE', 'Sorinomo');
insert into airport (id, name, country, city) values ('BTI', 'Barter Island LRRS Airport', 'US', 'Zwettl');
insert into airport (id, name, country, city) values ('KFE', 'Fortescue - Dave Forrest Aerodrome', 'AU', 'Providencia');
insert into airport (id, name, country, city) values ('INQ', 'Inisheer Aerodrome', 'IE', 'San Javier');
insert into airport (id, name, country, city) values ('LAD', 'Quatro de Fevereiro Airport', 'AO', 'Karonga');
insert into airport (id, name, country, city) values ('PCF', 'Potchefstroom Airport', 'ZA', 'Majāz al Bāb');
insert into airport (id, name, country, city) values ('HLB', 'Hillenbrand Industries Airport', 'US', 'Sinjil');
insert into airport (id, name, country, city) values ('VQS', 'Antonio Rivera Rodriguez Airport', 'PR', 'Neebing');
insert into airport (id, name, country, city) values ('ANH', 'Anuha Island Resort Airport', 'SB', 'Na Khu');
insert into airport (id, name, country, city) values ('OSI', 'Osijek Airport', 'HR', 'Trasak');
insert into airport (id, name, country, city) values ('ANJ', 'Zanaga Airport', 'CG', 'Cuyotenango');
insert into airport (id, name, country, city) values ('XNU', 'Nouna Airport', 'BF', 'Fuling');
insert into airport (id, name, country, city) values ('FFL', 'Fairfield Municipal Airport', 'US', 'Azua');
insert into airport (id, name, country, city) values ('DIP', 'Diapaga Airport', 'BF', 'Anibare');
insert into airport (id, name, country, city) values ('OKH', 'RAF Cottesmore', 'GB', 'Juxing');
insert into airport (id, name, country, city) values ('MKC', 'Charles B. Wheeler Downtown Airport', 'US', 'Gnieżdżewo');
insert into airport (id, name, country, city) values ('CIS', 'Canton Island Airport', 'KI', 'Smoky Lake');
insert into airport (id, name, country, city) values ('RGL', 'Piloto Civil N. Fernández Airport', 'AR', 'Eslāmābād');
insert into airport (id, name, country, city) values ('MOG', 'Mong Hsat Airport', 'MM', 'Černilov');
insert into airport (id, name, country, city) values ('TEM', 'Temora Airport', 'AU', 'Tengah');
insert into airport (id, name, country, city) values ('MQC', 'Miquelon Airport', 'PM', 'Cahors');
insert into airport (id, name, country, city) values ('OKY', 'Oakey Airport', 'AU', 'Dzhetygara');
insert into airport (id, name, country, city) values ('LLK', 'Lankaran International Airport', 'AZ', 'Piracuruca');
insert into airport (id, name, country, city) values ('THD', 'Tho Xuan Airport', 'VN', 'Banjar Geriana Kangin');
insert into airport (id, name, country, city) values ('ESF', 'Esler Regional Airport', 'US', 'Nancy');
insert into airport (id, name, country, city) values ('LLL', 'Lissadell Airport', 'AU', 'Bystré');
insert into airport (id, name, country, city) values ('GSS', 'Sabi Sabi Airport', 'ZA', 'Moca');
insert into airport (id, name, country, city) values ('SNM', 'San Ignacio de Moxos Airport', 'BO', 'Ribeiro');
insert into airport (id, name, country, city) values ('KSP', 'Kosipe Airport', 'PG', 'Cagmanaba');
insert into airport (id, name, country, city) values ('KWP', 'West Point Village Seaplane Base', 'US', 'Sumberdadi');
insert into airport (id, name, country, city) values ('SSE', 'Solapur Airport', 'IN', 'Sawangan');
insert into airport (id, name, country, city) values ('BIX', 'Keesler Air Force Base', 'US', 'Zhaitou');
insert into airport (id, name, country, city) values ('SMI', 'Samos Airport', 'GR', 'Chahe');
insert into airport (id, name, country, city) values ('IFO', 'Ivano-Frankivsk International Airport', 'UA', 'Miki');
insert into airport (id, name, country, city) values ('HSP', 'Ingalls Field', 'US', 'Oleszyce');
insert into airport (id, name, country, city) values ('DHG', 'Dalnegorsk Airport', 'RU', 'Qilin');
insert into airport (id, name, country, city) values ('NNL', 'Nondalton Airport', 'US', 'Klagen');
insert into airport (id, name, country, city) values ('EME', 'Emden Airport', 'DE', 'Matsubara');
insert into airport (id, name, country, city) values ('DHD', 'Durham Downs Airport', 'AU', 'Laju Kidul');
insert into airport (id, name, country, city) values ('CTZ', 'Sampson County Airport', 'US', 'Sinarbakti');
insert into airport (id, name, country, city) values ('GUH', 'Gunnedah Airport', 'AU', 'Raman');
insert into airport (id, name, country, city) values ('FDK', 'Frederick Municipal Airport', 'US', 'Enzan');
insert into airport (id, name, country, city) values ('PEF', 'Peenemünde Airport', 'DE', 'Goussainville');
insert into airport (id, name, country, city) values ('PEQ', 'Rio Paranaíba Airport', 'BR', 'Holoriang');
insert into airport (id, name, country, city) values ('SLL', 'Salalah Airport', 'OM', 'Mehrābpur');
insert into airport (id, name, country, city) values ('APV', 'Apple Valley Airport', 'US', 'Illela');
insert into airport (id, name, country, city) values ('HOO', 'Nhon Co Airfield', 'VN', 'San Vicente');
insert into airport (id, name, country, city) values ('DAA', 'Davison Army Air Field', 'US', 'Al Ghayl');
insert into airport (id, name, country, city) values ('NMB', 'Daman Airport', 'IN', 'Pawłosiów');
insert into airport (id, name, country, city) values ('SUM', 'Sumter Airport', 'US', 'Mirecourt');
insert into airport (id, name, country, city) values ('BJR', 'Bahir Dar Airport', 'ET', 'Banjar Desa');
insert into airport (id, name, country, city) values ('AXJ', 'Amakusa Airport', 'JP', 'Huayang');
insert into airport (id, name, country, city) values ('FOG', 'Foggia "Gino Lisa" Airport', 'IT', 'Solna');
insert into airport (id, name, country, city) values ('HRK', 'Kharkiv International Airport', 'UA', 'Manassas');
insert into airport (id, name, country, city) values ('OUD', 'Angads Airport', 'MA', 'Huskvarna');
insert into airport (id, name, country, city) values ('CAO', 'Clayton Municipal Airpark', 'US', 'Frolovo');
insert into airport (id, name, country, city) values ('AER', 'Sochi International Airport', 'RU', 'Huazhou');
insert into airport (id, name, country, city) values ('AEQ', 'EMBRAER - Unidade Gavião Peixoto Airport', 'BR', 'Sandviken');
insert into airport (id, name, country, city) values ('LWE', 'Lewoleba Airport', 'ID', 'Dalupirip');
insert into airport (id, name, country, city) values ('LWN', 'Gyumri Shirak Airport', 'AM', 'Gent');
insert into airport (id, name, country, city) values ('PBW', 'Hermanos Serdán International Airport', 'MX', 'Rogowo');
insert into airport (id, name, country, city) values ('KGA', 'Kananga Airport', 'CD', 'Aktsyabrski');
insert into airport (id, name, country, city) values ('DXR', 'Danbury Municipal Airport', 'US', 'Acul du Nord');
insert into airport (id, name, country, city) values ('LGI', 'Deadman''s Cay Airport', 'BS', 'Perstorp');
insert into airport (id, name, country, city) values ('SXL', 'Sligo Airport', 'IE', 'Dushi');
insert into airport (id, name, country, city) values ('TBF', 'Tabiteuea North Airport', 'KI', 'Trasak');
insert into airport (id, name, country, city) values ('PKG', 'Pulau Pangkor Airport', 'MY', 'Guabito');
insert into airport (id, name, country, city) values ('BCH', 'Cakung Airport', 'TL', 'Nové Město nad Metují');
insert into airport (id, name, country, city) values ('RKH', 'Rock Hill - York County Airport', 'US', 'Magnitka');
insert into airport (id, name, country, city) values ('FNH', 'Fincha Airport', 'ET', 'Olenegorsk');
insert into airport (id, name, country, city) values ('AOR', 'Sultan Abdul Halim Airport', 'MY', 'Tayabo');
insert into airport (id, name, country, city) values ('KBA', 'Kabala Airport', 'SL', 'Dmitriyevskaya');
insert into airport (id, name, country, city) values ('KOK', 'Kokkola-Pietarsaari Airport', 'FI', 'Krojo');
insert into airport (id, name, country, city) values ('GDG', 'Magdagachi Airport', 'RU', 'Palangan');
insert into airport (id, name, country, city) values ('CEA', 'Cessna Aircraft Field', 'US', 'Courbevoie');
insert into airport (id, name, country, city) values ('VXO', 'Växjö Kronoberg Airport', 'SE', 'Lubniewice');
insert into airport (id, name, country, city) values ('RCH', 'Almirante Padilla Airport', 'CO', 'Ambian');
insert into airport (id, name, country, city) values ('DAB', 'Daytona Beach International Airport', 'US', 'Kangdong-ŭp');
insert into airport (id, name, country, city) values ('SEK', 'Srednekolymsk Airport', 'RU', 'Sanshui');
insert into airport (id, name, country, city) values ('LWK', 'Lerwick / Tingwall Airport', 'GB', 'Mirów');
insert into airport (id, name, country, city) values ('PAZ', 'El Tajín National Airport', 'MX', 'Bogale');
insert into airport (id, name, country, city) values ('ISE', 'Süleyman Demirel International Airport', 'TR', 'Mehrābpur');
insert into airport (id, name, country, city) values ('DSN', 'Ordos Ejin Horo Airport', 'CN', 'Totoral');
insert into airport (id, name, country, city) values ('ORN', 'Es Senia Airport', 'DZ', 'Round Rock');
insert into airport (id, name, country, city) values ('SYA', 'Eareckson Air Station', 'US', 'Oviedo');
insert into airport (id, name, country, city) values ('STT', 'Cyril E. King Airport', 'VI', 'Skoczów');
insert into airport (id, name, country, city) values ('HUF', 'Terre Haute Regional Airport, Hulman Field', 'US', 'Châlons-en-Champagne');
insert into airport (id, name, country, city) values ('SHY', 'Shinyanga Airport', 'TZ', 'Vila Franca do Campo');
insert into airport (id, name, country, city) values ('FBM', 'Lubumbashi International Airport', 'CD', 'Itapuranga');
insert into airport (id, name, country, city) values ('DCU', 'Pryor Field Regional Airport', 'US', 'Rungkang');
insert into airport (id, name, country, city) values ('MBZ', 'Maués Airport', 'BR', 'Córdoba');
insert into airport (id, name, country, city) values ('PQI', 'Northern Maine Regional Airport at Presque Isle', 'US', 'Tangzhai');
insert into airport (id, name, country, city) values ('WAZ', 'Warwick Airport', 'AU', 'Sintra');
insert into airport (id, name, country, city) values ('GLT', 'Gladstone Airport', 'AU', 'Springfield');
insert into airport (id, name, country, city) values ('LPA', 'Gran Canaria Airport', 'ES', 'Oskarshamn');
insert into airport (id, name, country, city) values ('MGF', 'Regional de Maringá - Sílvio Nane Junior Airport', 'BR', 'Blaye');
insert into airport (id, name, country, city) values ('NGE', 'N''Gaoundéré Airport', 'CM', 'Manaus');
insert into airport (id, name, country, city) values ('OLM', 'Olympia Regional Airport', 'US', 'Kalinkavichy');
insert into airport (id, name, country, city) values ('LCD', 'Louis Trichardt Airport', 'ZA', 'Akron');
insert into airport (id, name, country, city) values ('CKV', 'Clarksville–Montgomery County Regional Airport', 'US', 'Cruzília');
insert into airport (id, name, country, city) values ('GGG', 'East Texas Regional Airport', 'US', 'Dalong');
insert into airport (id, name, country, city) values ('RVY', 'Presidente General Don Oscar D. Gestido International Airport', 'UY', 'Heshan');
insert into airport (id, name, country, city) values ('YWR', 'White River Seaplane Base', 'CA', 'Maleevsk');
insert into airport (id, name, country, city) values ('PBC', 'Hermanos Serdán International Airport', 'MX', 'Suicheng');
insert into airport (id, name, country, city) values ('MPL', 'Montpellier-Méditerranée Airport', 'FR', 'Pancoran');
insert into airport (id, name, country, city) values ('AGY', 'Argyle Downs Airport', 'AU', 'Gusang');
insert into airport (id, name, country, city) values ('TCS', 'Truth Or Consequences Municipal Airport', 'US', 'Sanxi');
insert into airport (id, name, country, city) values ('BSU', 'Basankusu Airport', 'CD', 'Rakičan');
insert into airport (id, name, country, city) values ('PBR', 'Puerto Barrios Airport', 'GT', 'Laojie');
insert into airport (id, name, country, city) values ('TBP', 'Capitan FAP Pedro Canga Rodriguez Airport', 'PE', 'Bandar-e Torkaman');
insert into airport (id, name, country, city) values ('SRZ', 'El Trompillo Airport', 'BO', 'Xingtai');
insert into airport (id, name, country, city) values ('PVC', 'Provincetown Municipal Airport', 'US', 'Acacías');
insert into airport (id, name, country, city) values ('BKA', 'Bykovo Airport', 'RU', 'Elena');
insert into airport (id, name, country, city) values ('ATX', 'Atbasar Airport', 'KZ', 'George Town');
insert into airport (id, name, country, city) values ('SCN', 'Saarbrücken Airport', 'DE', 'Nicolet');
insert into airport (id, name, country, city) values ('KSB', 'Kasonombe Airport', 'PG', 'Xiamazhuang');
insert into airport (id, name, country, city) values ('KAU', 'Kauhava Airport', 'FI', 'Ryazanskaya');
insert into airport (id, name, country, city) values ('WWP', 'Whale Pass Seaplane Float Harbor Facility', 'US', 'San Pedro Pinula');
insert into airport (id, name, country, city) values ('NTE', 'Nantes Atlantique Airport', 'FR', 'San Rafael');
insert into airport (id, name, country, city) values ('SAY', 'Siena-Ampugnano Airport', 'IT', 'Mladá Boleslav');
insert into airport (id, name, country, city) values ('BKN', 'Balkanabat Airport', 'TM', 'Tualeu');
insert into airport (id, name, country, city) values ('DUT', 'Unalaska Airport', 'US', 'Huangwan');
insert into airport (id, name, country, city) values ('FUK', 'Fukuoka Airport', 'JP', 'Foros da Catrapona');
insert into airport (id, name, country, city) values ('VPG', 'Vipingo Estate Airport', 'KE', 'Conceição do Jacuípe');
insert into airport (id, name, country, city) values ('AUW', 'Abu Rudeis Airport', 'EG', 'Perené');
insert into airport (id, name, country, city) values ('WNN', 'Wunnumin Lake Airport', 'CA', 'Bom Despacho');
insert into airport (id, name, country, city) values ('ESR', 'Ricardo García Posada Airport', 'CL', 'Litian');
insert into airport (id, name, country, city) values ('YDB', 'Burwash Airport', 'CA', 'Jangheung');
insert into airport (id, name, country, city) values ('WAR', 'Waris Airport', 'ID', 'Changyi');
insert into airport (id, name, country, city) values ('FAB', 'Farnborough Airport', 'GB', 'Burujul');
insert into airport (id, name, country, city) values ('AXF', 'Alxa Left Banner Bayanhot Airport', 'CN', 'Bejuco');
insert into airport (id, name, country, city) values ('HIF', 'Hill Air Force Base', 'US', 'Migori');
insert into airport (id, name, country, city) values ('LLS', 'Alferez Armando Rodriguez Airport', 'AR', 'Luján de Cuyo');
insert into airport (id, name, country, city) values ('MRG', 'Mareeba Airport', 'AU', 'Fantan');
insert into airport (id, name, country, city) values ('KVG', 'Kavieng Airport', 'PG', 'Pasłęk');
insert into airport (id, name, country, city) values ('ZCL', 'General Leobardo C. Ruiz International Airport', 'MX', 'La Soledad');
insert into airport (id, name, country, city) values ('ULG', 'Ulgii Mongolei Airport', 'MN', 'Ayapel');
insert into airport (id, name, country, city) values ('CHS', 'Charleston Air Force Base-International Airport', 'US', 'Kertayuga');
insert into airport (id, name, country, city) values ('MXX', 'Mora Airport', 'SE', 'Hînceşti');
insert into airport (id, name, country, city) values ('XWW', 'Montauban Airport', 'FR', 'Chamouny');
insert into airport (id, name, country, city) values ('CMK', 'Club Makokola Airport', 'MW', 'Darfield');
insert into airport (id, name, country, city) values ('AFO', 'Afton Municipal Airport', 'US', 'Cliza');
insert into airport (id, name, country, city) values ('FSD', 'Joe Foss Field Airport', 'US', 'Bakungan');
insert into airport (id, name, country, city) values ('UNR', 'Öndörkhaan Airport', 'MN', 'Santo Antônio de Posse');
insert into airport (id, name, country, city) values ('AGT', 'Guarani International Airport', 'PY', 'Kyenjojo');
insert into airport (id, name, country, city) values ('TPX', 'Tupai Airport', 'PF', 'Zhentou');
insert into airport (id, name, country, city) values ('LKL', 'Banak Airport', 'NO', 'Luchenza');
insert into airport (id, name, country, city) values ('CTP', 'Carutapera Airport', 'BR', 'Parque Industrial');
insert into airport (id, name, country, city) values ('LWA', 'Lebak Rural Airport', 'PH', 'Burns Lake');
insert into airport (id, name, country, city) values ('YWA', 'Petawawa Airport', 'CA', 'Las Americas');
insert into airport (id, name, country, city) values ('CKL', 'Chkalovskiy Air Base', 'RU', 'Alvide');
insert into airport (id, name, country, city) values ('GMW', 'La Gomera Airport', 'ES', 'Pital');
insert into airport (id, name, country, city) values ('NQL', 'Niquelândia Airport', 'BR', 'Xindeng');
insert into airport (id, name, country, city) values ('UNI', 'Union Island International Airport', 'VC', 'Tulsa');
insert into airport (id, name, country, city) values ('LWT', 'Lewistown Municipal Airport', 'US', 'Padangtepung');
insert into airport (id, name, country, city) values ('QCY', 'RAF Coningsby', 'GB', 'Fenyan');
insert into airport (id, name, country, city) values ('CMY', 'Sparta Fort Mc Coy Airport', 'US', 'Liangkou');
insert into airport (id, name, country, city) values ('SNR', 'Saint-Nazaire-Montoir Airport', 'FR', 'Qingyang');
insert into airport (id, name, country, city) values ('LCC', 'Lecce Galatina Air Base', 'IT', 'Qingminghe');
insert into airport (id, name, country, city) values ('MGR', 'Moultrie Municipal Airport', 'US', 'Ḩawallī');
insert into airport (id, name, country, city) values ('UDI', 'Ten. Cel. Aviador César Bombonato Airport', 'BR', 'Mogi Mirim');
insert into airport (id, name, country, city) values ('PVE', 'El Porvenir Airport', 'PA', 'Aquin');
insert into airport (id, name, country, city) values ('ZRH', 'Zürich Airport', 'CH', 'Sv. Anton');
insert into airport (id, name, country, city) values ('VPS', 'Destin-Ft Walton Beach Airport', 'US', 'Vilkija');
insert into airport (id, name, country, city) values ('WRL', 'Worland Municipal Airport', 'US', 'Oemofa');
insert into airport (id, name, country, city) values ('HPY', 'Baytown Airport', 'US', 'Kuala Lumpur');
insert into airport (id, name, country, city) values ('LTP', 'Lyndhurst Airport', 'AU', 'Guararema');
insert into airport (id, name, country, city) values ('LTW', 'Caçapava do Sul Airport', 'BR', 'Talibura');
insert into airport (id, name, country, city) values ('LAB', 'Lab Lab Airport', 'PG', 'Dasha');
insert into airport (id, name, country, city) values ('KGK', 'Koliganek Airport', 'US', 'Batasan');
insert into airport (id, name, country, city) values ('MGQ', 'Aden Adde International Airport', 'SO', 'Herby');
insert into airport (id, name, country, city) values ('ASK', 'Yamoussoukro Airport', 'CI', 'Lazaro Cardenas');
insert into airport (id, name, country, city) values ('BPY', 'Besalampy Airport', 'MG', 'Fontinha');
insert into airport (id, name, country, city) values ('POY', 'Powell Municipal Airport', 'US', 'Naviraí');
insert into airport (id, name, country, city) values ('VCH', 'Vichadero Airport', 'UY', 'Daixi');
insert into airport (id, name, country, city) values ('CHO', 'Charlottesville Albemarle Airport', 'US', 'Pitogo');
insert into airport (id, name, country, city) values ('LGL', 'Long Lellang Airport', 'MY', 'Unaí');
insert into airport (id, name, country, city) values ('YET', 'Edson Airport', 'CA', 'Fanrong');
insert into airport (id, name, country, city) values ('YSY', 'Sachs Harbour (David Nasogaluak Jr. Saaryuaq) Airport', 'CA', 'Itajubá');
insert into airport (id, name, country, city) values ('BZT', 'Eagle Air Park', 'US', 'Orneta');
insert into airport (id, name, country, city) values ('AYA', 'Ayapel Airport', 'CO', 'Pasto');
insert into airport (id, name, country, city) values ('BCL', 'Barra del Colorado Airport', 'CR', 'Berendeyevo');
insert into airport (id, name, country, city) values ('SVI', 'Eduardo Falla Solano Airport', 'CO', 'Frederiksberg');
insert into airport (id, name, country, city) values ('UTW', 'Mutare Airport', 'ZW', 'Zherdevka');
insert into airport (id, name, country, city) values ('AMW', 'Ames Municipal Airport', 'US', 'Klyuchevsk');
insert into airport (id, name, country, city) values ('KNR', 'Jam Airport', 'IR', 'Yur’yevets');
insert into airport (id, name, country, city) values ('MWO', 'Middletown Regional Airport', 'US', 'Damatulan');
insert into airport (id, name, country, city) values ('HHR', 'Jack Northrop Field Hawthorne Municipal Airport', 'US', 'Llano Largo');
insert into airport (id, name, country, city) values ('MVI', 'Manetai Airport', 'PG', 'Tominian');
insert into airport (id, name, country, city) values ('LPN', 'Leron Plains Airport', 'PG', 'København');
insert into airport (id, name, country, city) values ('TGA', 'Tengah Air Base', 'SG', 'Xiaoyi');
insert into airport (id, name, country, city) values ('BHV', 'Bahawalpur Airport', 'PK', 'Spitsevka');
insert into airport (id, name, country, city) values ('HSV', 'Huntsville International Carl T Jones Field', 'US', 'Zhangjiaji');
insert into airport (id, name, country, city) values ('NBH', 'Nambucca Heads Airport', 'AU', 'Tost');
insert into airport (id, name, country, city) values ('RRR', 'Raroia Airport', 'PF', 'Nazareth');
insert into airport (id, name, country, city) values ('XNN', 'Xining Caojiabu Airport', 'CN', 'Ostrowsko');
insert into airport (id, name, country, city) values ('VQQ', 'Cecil Airport', 'US', 'Boden');
insert into airport (id, name, country, city) values ('KEI', 'Kepi Airport', 'ID', 'Khānaqāh');
insert into airport (id, name, country, city) values ('TME', 'Gustavo Vargas Airport', 'CO', 'Heichengzi');
insert into airport (id, name, country, city) values ('MAU', 'Maupiti Airport', 'PF', 'Oslo');
insert into airport (id, name, country, city) values ('TEV', 'Teruel Airport', 'ES', 'Chisong');
insert into airport (id, name, country, city) values ('AIF', 'Marcelo Pires Halzhausen Airport', 'BR', 'Salmi');
insert into airport (id, name, country, city) values ('DPT', 'Deputatskiy Airport', 'RU', 'Tanjungbatu');
insert into airport (id, name, country, city) values ('ROH', 'Robinhood Airport', 'AU', 'Örebro');
insert into airport (id, name, country, city) values ('SFB', 'Orlando Sanford International Airport', 'US', 'Nizhniy Lomov');
insert into airport (id, name, country, city) values ('AGG', 'Angoram Airport', 'PG', 'Sidomakmur');
insert into airport (id, name, country, city) values ('PMY', 'El Tehuelche Airport', 'AR', 'Černošice');
insert into airport (id, name, country, city) values ('ZOS', 'Cañal Bajo Carlos - Hott Siebert Airport', 'CL', 'Jaunpiebalga');
insert into airport (id, name, country, city) values ('KFS', 'Kastamonu Airport', 'TR', 'Mamanguape');
insert into airport (id, name, country, city) values ('BDK', 'Soko Airport', 'CI', 'Proástion');
insert into airport (id, name, country, city) values ('AUF', 'Auxerre-Branches Airport', 'FR', 'Aleshtar');
insert into airport (id, name, country, city) values ('RVW', 'Presidente General Don Oscar D. Gestido International Airport', 'UY', 'San Miguel');
insert into airport (id, name, country, city) values ('JCK', 'Julia Creek Airport', 'AU', 'Szydłowo');
insert into airport (id, name, country, city) values ('GRN', 'Gordon Municipal Airport', 'US', 'Dolní Dvořiště');
insert into airport (id, name, country, city) values ('DVO', 'Francisco Bangoy International Airport', 'PH', 'Tarbes');
insert into airport (id, name, country, city) values ('YHE', 'Hope Airport', 'CA', 'Chishui');
insert into airport (id, name, country, city) values ('HGD', 'Hughenden Airport', 'AU', 'Washington');
insert into airport (id, name, country, city) values ('TKZ', 'Tokoroa Airfield', 'NZ', 'Phumĭ Véal Srê');
insert into airport (id, name, country, city) values ('IMO', 'Zemio Airport', 'CF', 'Rainis');
insert into airport (id, name, country, city) values ('TAR', 'Taranto-Grottaglie "Marcello Arlotta" Airport', 'IT', 'Olenegorsk');
insert into airport (id, name, country, city) values ('NIF', 'Camp Nifty Airport', 'AU', 'Pacora');
insert into airport (id, name, country, city) values ('HBE', 'Borg El Arab International Airport', 'EG', 'Lefkímmi');
insert into airport (id, name, country, city) values ('ZTA', 'Tureia Airport', 'PF', 'Kasungu');
insert into airport (id, name, country, city) values ('PUM', 'Pomala Airport', 'ID', 'Hongshunli');
insert into airport (id, name, country, city) values ('YCF', 'Cortes Bay Water Aerodrome', 'CA', 'Cipari');
insert into airport (id, name, country, city) values ('TTC', 'Las Breas Airport', 'CL', 'Palmar de Varela');
insert into airport (id, name, country, city) values ('KIY', 'Kilwa Masoko Airport', 'TZ', 'São Domingos');
insert into airport (id, name, country, city) values ('STL', 'St Louis Lambert International Airport', 'US', 'Nanzhao');
insert into airport (id, name, country, city) values ('QKX', 'Kautokeino Air Base', 'NO', 'Kanuma');
insert into airport (id, name, country, city) values ('SQK', 'Sidi Barrani Airport', 'EG', 'Orlando');
insert into airport (id, name, country, city) values ('TPC', 'Tarapoa Airport', 'EC', 'Karawatu');
insert into airport (id, name, country, city) values ('BNY', 'Bellona/Anua Airport', 'SB', 'Bobowo');
insert into airport (id, name, country, city) values ('FID', 'Elizabeth Field', 'US', 'Duba-Yurt');
insert into airport (id, name, country, city) values ('DOC', 'Dornoch Airfield', 'GB', 'Tymbark');
insert into airport (id, name, country, city) values ('OMK', 'Omak Airport', 'US', 'Pilar');
insert into airport (id, name, country, city) values ('DCK', 'Dahl Creek Airport', 'US', 'Lampa');
insert into airport (id, name, country, city) values ('AWK', 'Wake Island Airfield', 'UM', 'Baoluan');
insert into airport (id, name, country, city) values ('DEE', 'Mendeleyevo Airport', 'RU', 'Pugeran');
insert into airport (id, name, country, city) values ('MFA', 'Mafia Island Airport', 'TZ', 'Zhangxi');
insert into airport (id, name, country, city) values ('EUM', 'Neumünster Airport', 'DE', 'Louisville');
insert into airport (id, name, country, city) values ('FXY', 'Forest City Municipal Airport', 'US', 'Dongxi');
insert into airport (id, name, country, city) values ('BLE', 'Borlange Airport', 'SE', 'Niños Heroes');
insert into airport (id, name, country, city) values ('SWM', 'Suia-Missu Airport', 'BR', 'Panyingkiran');
insert into airport (id, name, country, city) values ('LMC', 'El Refugio/La Macarena Airport', 'CO', 'Lidu');
insert into airport (id, name, country, city) values ('BRK', 'Bourke Airport', 'AU', 'Oeba');
insert into airport (id, name, country, city) values ('KOT', 'Kotlik Airport', 'US', 'Spiczyn');
insert into airport (id, name, country, city) values ('TSU', 'Tabiteuea South Airport', 'KI', 'Draguignan');
insert into airport (id, name, country, city) values ('RSH', 'Russian Mission Airport', 'US', 'Šentrupert');
insert into airport (id, name, country, city) values ('GZT', 'Gaziantep International Airport', 'TR', 'Subottsi');
insert into airport (id, name, country, city) values ('FTA', 'Futuna Airport', 'VU', 'Chai Nat');
insert into airport (id, name, country, city) values ('LKW', 'Lekhwair Airport', 'OM', 'Dajanrurung');
insert into airport (id, name, country, city) values ('MVK', 'Mulka Airport', 'AU', 'Beloha');
insert into airport (id, name, country, city) values ('CPL', 'Chaparral Airport', 'CO', 'Milaor');
insert into airport (id, name, country, city) values ('MLQ', 'Malalaua Airport', 'PG', 'Jincheng');
insert into airport (id, name, country, city) values ('EFL', 'Kefallinia Airport', 'GR', 'Yong’an');
insert into airport (id, name, country, city) values ('CAW', 'Clayton Municipal Airpark', 'US', 'Las Flores');
insert into airport (id, name, country, city) values ('KMK', 'Makabana Airport', 'CG', 'Guxi');
insert into airport (id, name, country, city) values ('CDF', 'Cortina Airport', 'IT', 'Borzytuchom');
insert into airport (id, name, country, city) values ('TGH', 'Tongoa Airport', 'VU', 'Priboj');
insert into airport (id, name, country, city) values ('AOC', 'Altenburg-Nobitz Airport', 'DE', 'Beijiang');
insert into airport (id, name, country, city) values ('MFX', 'Méribel Altiport', 'FR', 'Shilong');
insert into airport (id, name, country, city) values ('ACD', 'Alcides Fernández Airport', 'CO', 'Peterhof');
insert into airport (id, name, country, city) values ('YSL', 'St Leonard Airport', 'CA', 'El Cantón');
insert into airport (id, name, country, city) values ('GDL', 'Don Miguel Hidalgo Y Costilla International Airport', 'MX', 'Bayanbulag');
insert into airport (id, name, country, city) values ('YQN', 'Nakina Airport', 'CA', 'Morro Agudo');
insert into airport (id, name, country, city) values ('EDQ', 'Erandique Airport', 'HN', 'Czyżowice');
insert into airport (id, name, country, city) values ('YFA', 'Fort Albany Airport', 'CA', 'Sepahua');
insert into airport (id, name, country, city) values ('UAE', 'Mount Aue Airport', 'PG', 'Kemendung');
insert into airport (id, name, country, city) values ('BPK', 'Biangabip Airport', 'PG', 'Arcossó');
insert into airport (id, name, country, city) values ('HOT', 'Memorial Field', 'US', 'Nyalindung');
insert into airport (id, name, country, city) values ('TSS', 'East 34th Street Heliport', 'US', 'Purral');
insert into airport (id, name, country, city) values ('QPS', 'Campo Fontenelle Airport', 'BR', 'Iberia');
insert into airport (id, name, country, city) values ('FRS', 'Mundo Maya International Airport', 'GT', 'Semikarakorsk');
insert into airport (id, name, country, city) values ('CFQ', 'Creston Valley Regional Airport - Art Sutcliffe Field', 'CA', 'Hot');
insert into airport (id, name, country, city) values ('ORT', 'Northway Airport', 'US', 'Tongxing');
insert into airport (id, name, country, city) values ('PJC', 'Dr Augusto Roberto Fuster International Airport', 'PY', 'Tīrān');
insert into airport (id, name, country, city) values ('NLG', 'Nelson Lagoon Airport', 'US', 'Piggotts');
insert into airport (id, name, country, city) values ('TMG', 'Tomanggong Airport', 'MY', 'Ouango');
insert into airport (id, name, country, city) values ('MIT', 'Shafter Airport - Minter Field', 'US', 'Pirca');
insert into airport (id, name, country, city) values ('CXL', 'Calexico International Airport', 'US', 'Padaimut');
insert into airport (id, name, country, city) values ('CDI', 'Cachoeiro do Itapemirim Airport', 'BR', 'Neftçala');
insert into airport (id, name, country, city) values ('REC', 'Guararapes - Gilberto Freyre International Airport', 'BR', 'Odiong');
insert into airport (id, name, country, city) values ('UKX', 'Ust-Kut Airport', 'RU', 'Autun');
insert into airport (id, name, country, city) values ('FIN', 'Finschhafen Airport', 'PG', 'Zhongxiang');
insert into airport (id, name, country, city) values ('TJN', 'Takume Airport', 'PF', 'Kulpin');
insert into airport (id, name, country, city) values ('MEB', 'Melbourne Essendon Airport', 'AU', 'Siyabuswa');
insert into airport (id, name, country, city) values ('BBX', 'Wings Field', 'US', 'Cestas');
insert into airport (id, name, country, city) values ('PIL', 'Carlos Miguel Gimenez Airport', 'PY', 'Ikalamavony');
insert into airport (id, name, country, city) values ('CEQ', 'Bob Sikes Airport', 'US', 'Tangkou');
insert into airport (id, name, country, city) values ('DBV', 'Dubrovnik Airport', 'HR', 'Rauco');
insert into airport (id, name, country, city) values ('YCU', 'Yuncheng Guangong Airport', 'CN', 'Recarei');
insert into airport (id, name, country, city) values ('LBS', 'Labasa Airport', 'FJ', 'Mitzpe Ramon');
insert into airport (id, name, country, city) values ('LTL', 'Lastourville Airport', 'GA', 'Kendaruan');
insert into airport (id, name, country, city) values ('INO', 'Inongo Airport', 'CD', 'Kemisē');
