version: "3.9"

services:
  postgresql:
    image: postgres:14
    container_name: itmo-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - postgres_itmo_data:/var/lib/postgresql/data
    networks:
      - postgres_itmo_network

volumes:
  postgres_itmo_data:
    name: postgres_itmo_data

networks:
  postgres_itmo_network:
    name: postgres_itmo_network
